/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlarmsRouteImport } from './routes/alarms'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FirewallRouteImport } from './routes/firewall'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as PlantRouteImport } from './routes/plant'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as MachinesIndexRouteImport } from './routes/machines.index'
import { Route as MachinesIdRouteImport } from './routes/machines.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlarmsRoute = AlarmsRouteImport.update({
  id: '/alarms',
  path: '/alarms',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FirewallRoute = FirewallRouteImport.update({
  id: '/firewall',
  path: '/firewall',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantRoute = PlantRouteImport.update({
  id: '/plant',
  path: '/plant',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesIndexRoute = MachinesIndexRouteImport.update({
  id: '/machines/',
  path: '/machines/',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesIdRoute = MachinesIdRouteImport.update({
  id: '/machines/$id',
  path: '/machines/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alarms': typeof AlarmsRoute
  '/company': typeof CompanyRoute
  '/dashboard': typeof DashboardRoute
  '/firewall': typeof FirewallRoute
  '/maintenance': typeof MaintenanceRoute
  '/plant': typeof PlantRoute
  '/process': typeof ProcessRoute
  '/quality': typeof QualityRoute
  '/machines/$id': typeof MachinesIdRoute
  '/machines/': typeof MachinesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alarms': typeof AlarmsRoute
  '/company': typeof CompanyRoute
  '/dashboard': typeof DashboardRoute
  '/firewall': typeof FirewallRoute
  '/maintenance': typeof MaintenanceRoute
  '/plant': typeof PlantRoute
  '/process': typeof ProcessRoute
  '/quality': typeof QualityRoute
  '/machines/$id': typeof MachinesIdRoute
  '/machines': typeof MachinesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alarms': typeof AlarmsRoute
  '/company': typeof CompanyRoute
  '/dashboard': typeof DashboardRoute
  '/firewall': typeof FirewallRoute
  '/maintenance': typeof MaintenanceRoute
  '/plant': typeof PlantRoute
  '/process': typeof ProcessRoute
  '/quality': typeof QualityRoute
  '/machines/$id': typeof MachinesIdRoute
  '/machines/': typeof MachinesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alarms'
    | '/company'
    | '/dashboard'
    | '/firewall'
    | '/maintenance'
    | '/plant'
    | '/process'
    | '/quality'
    | '/machines/$id'
    | '/machines/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alarms'
    | '/company'
    | '/dashboard'
    | '/firewall'
    | '/maintenance'
    | '/plant'
    | '/process'
    | '/quality'
    | '/machines/$id'
    | '/machines'
  id:
    | '__root__'
    | '/'
    | '/alarms'
    | '/company'
    | '/dashboard'
    | '/firewall'
    | '/maintenance'
    | '/plant'
    | '/process'
    | '/quality'
    | '/machines/$id'
    | '/machines/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlarmsRoute: typeof AlarmsRoute
  CompanyRoute: typeof CompanyRoute
  DashboardRoute: typeof DashboardRoute
  FirewallRoute: typeof FirewallRoute
  MaintenanceRoute: typeof MaintenanceRoute
  PlantRoute: typeof PlantRoute
  ProcessRoute: typeof ProcessRoute
  QualityRoute: typeof QualityRoute
  MachinesIdRoute: typeof MachinesIdRoute
  MachinesIndexRoute: typeof MachinesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alarms': {
      id: '/alarms'
      path: '/alarms'
      fullPath: '/alarms'
      preLoaderRoute: typeof AlarmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firewall': {
      id: '/firewall'
      path: '/firewall'
      fullPath: '/firewall'
      preLoaderRoute: typeof FirewallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plant': {
      id: '/plant'
      path: '/plant'
      fullPath: '/plant'
      preLoaderRoute: typeof PlantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines/': {
      id: '/machines/'
      path: '/machines'
      fullPath: '/machines/'
      preLoaderRoute: typeof MachinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines/$id': {
      id: '/machines/$id'
      path: '/machines/$id'
      fullPath: '/machines/$id'
      preLoaderRoute: typeof MachinesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlarmsRoute: AlarmsRoute,
  CompanyRoute: CompanyRoute,
  DashboardRoute: DashboardRoute,
  FirewallRoute: FirewallRoute,
  MaintenanceRoute: MaintenanceRoute,
  PlantRoute: PlantRoute,
  ProcessRoute: ProcessRoute,
  QualityRoute: QualityRoute,
  MachinesIdRoute: MachinesIdRoute,
  MachinesIndexRoute: MachinesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
